/home/miki/poly/.tox$ /usr/bin/python3.2mu /usr/local/lib/python2.7/dist-packages/virtualenv.py --no-site-packages py32 >py32/log/0.log
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/site.py", line 73, in <module>
    __boot()
  File "/usr/local/lib/python2.7/dist-packages/site.py", line 48, in __boot
    addsitedir(item)
  File "/home/miki/poly/.tox/py32/lib/python3.2/site.py", line 203, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/miki/poly/.tox/py32/lib/python3.2/site.py", line 172, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
ImportError: No module named new
Error processing line 1 of /usr/local/lib/python2.7/dist-packages/lazr.restfulclient-0.12.0-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.2/site.py", line 156, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ImportError: No module named new

Remainder of file ignored
Error processing line 1 of /usr/local/lib/python2.7/dist-packages/virtualenvwrapper-2.7.1-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.2/site.py", line 156, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ImportError: No module named new

Remainder of file ignored
Error processing line 1 of /usr/local/lib/python2.7/dist-packages/virtualenvwrapper-2.8-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.2/site.py", line 156, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ImportError: No module named new

Remainder of file ignored
Error processing line 1 of /usr/local/lib/python2.7/dist-packages/zope.interface-3.7.0-py2.7-nspkg.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.2/site.py", line 156, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ImportError: No module named new

Remainder of file ignored
The --no-site-packages flag is deprecated; it is now the default behavior.
New python executable in py32/bin/python3.2mu
Also creating executable in py32/bin/python
ERROR: The executable py32/bin/python3.2mu is not functioning
ERROR: It thinks sys.prefix is '/home/miki/poly/.tox' (should be '/home/miki/poly/.tox/py32')
ERROR: virtualenv is not compatible with this system or executable
